project:
  type: website
  output-dir: docs

website:
  title: "3-PG User Guide"
  sidebar:
    style: "docked"
    search: true
    logo: /media/3PG_Logo_Small.png
    logo-alt: "Website logo image"
    contents:
      - href: index.qmd
        text: Home
      - Section_1.qmd
      - Section_2.qmd
      - Section_3.qmd
      - Section_4.qmd
      - Section_5.qmd
      - Section_6.qmd
      - Section_7.qmd
      - Section_8.qmd
      
  page-footer:
    #left: <a href="https://irsslab.forestry.ubc.ca/" target="_blank"><img src="media/IRSS_logo_colour.png" alt="IRSS Logo" style="height:50px;"></a>
    right: <img src="media/logos_footer_2.png" alt="Logo" style="height:50px;">
    #center: <img src="media/3PG_Logo.png" alt="Logo" style="height:50px;">

format:
  html:
    theme: flatly
    css: /styles.css
    toc: true
    
editor: visual

