project:
  type: website
  output-dir: docs

website:
  title: "3-PG User Guide"
  sidebar:
    style: "docked"
    search: true
    logo: /media/3PG_Logo.png
    logo-alt: "Website logo image"
    contents:
      - href: index.qmd
        text: Home
      - Section_1.qmd
      - Section_2.qmd
      - Section_3.qmd
      - Section_4.qmd
      - Section_5.qmd
      - Section_6.qmd
      - Section_7.qmd
      
  page-footer:
    left: <img src="media/IRSS_logo_colour.png" alt="Logo" style="height:50px;">
    right: <img src="media/BP_logo.png" alt="Logo" style="height:50px;">
    #center: <img src="media/3PG_Logo.png" alt="Logo" style="height:50px;">

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

