---
title: "Input Datasets"
---

3-PG requires climatic data, data describing the physical properties of the site, and a species-specific parameter file. The C++ implementation of 3-PG is designed to provide spatially explicit estimates of forest growth parameters, which means that rasters can be used for any parameter that varies across the landscape, while constants can be used for those that do not. Below is a summary of the parameters that are required for 3-PG, as well data preparation requirements.

### Climate Data

The following climate data is required for 3-PG to run:

``` {.custom-block style="background-color: #f0f0f0; color: black;"}
Monthly means of maximum daily temperature (ºC)
Monthly means of minimum daily temperature (ºC)
Monthly mean rainfall (mm month-1)
Monthly mean short-wave radiation (MJ m-2 d-1)
Frost days per month
```

Climate data can be found from a variety of sources. In North America, [ClimateNA](https://climatena.ca/) is commonly used. ClimateNA is a free software package that generates scale-free climate data, and can use a digital elevation model (DEM) to produce gridded data at any spatial resolution. Both past and future climate projections can be generated; you can read more about the methodology to derive these estimates [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0156720)[^1] and [here](https://rmets.onlinelibrary.wiley.com/doi/10.1002/joc.7566)[^2].

[^1]: Wang T, Hamann A, Spittlehouse D, Carroll C (2016) [Locally Downscaled and Spatially Customizable Climate Data for Historical and Future Periods for North Americ](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0156720)a. PLoS ONE 11(6): e0156720. doi:10.1371/journal.pone.0156720

[^2]: Mahony, CR, Wang, T; Hamann, A and Cannon, AJ, 2022. A CMIP6 ensemble for downscaled monthly climate normals over North America. International Journal of Climatology 42 (11), 5871-5891 DOI: https://doi.org/10.1002/joc.7566

### Site Characteristics

Site factors required include latitude, soil water information, and soil descriptors:

``` custom-block
Latitude (site or pixel latitude)
Maximum available soil water (mm)
Minimum available soil water (mm)
Soil class (1-4, ? for default)
Soil fertility rating (0-1)
```

Depending on where your simulations occur, these layers may be freely available, while others can be derived from auxiliary data such as a DEM. \[**addition of CO2 to come**\].

In addition to the physical site conditions, the initial conditions for a stand need to be defined. This includes information about the stem, root, and foliage biomass (t ha^-1^), initial stocking (trees ha^-1^), and soil water (mm) at the start of the simulation. Initial stem, root, and foliage biomass are commonly given the values 6 (t ha^-1^), 3 (t ha^-1^), and 1 (t ha^-1^) respectively when a stand is being initialized from a seedling. The full list of site conditions are found below:

``` custom-block
Start age of the trees at the start of the simulation
Start month of the simulation
Year the stand was planted
Initial foliage biomass
Initial root biomass
Initial stem biomass
Initial stem number
Initial available soil water
```

### Data Preparation

Rasters are required to be spatially aligned; they need to share identical extent, resolution, and projection information. The 3-PG executable accesses rasters through the command line, and as such their path is hard coded into the parameter files. It is therefore recommended to place the rasters in a logical folder structure.

### Species Parameters

Parameters characterizing the species of interest is required for 3-PG. These parameters often exist for common commercial species such as **examples**. The full list of required parameters are provided below:

``` custom-block
"Foliage:stem partitioning ratio @ D=2 cm"        
"Foliage:stem partitioning ratio @ D=20 cm"        
"Constant in the stem mass v. diam. relationship"        
"Power in the stem mass v. diam. relationship"        
"Maximum fraction of NPP to roots"        
"Minimum fraction of NPP to roots"        
"Minimum temperature for growth"        
"Optimum temperature for growth"        
"Maximum temperature for growth"        
"Days production lost per frost day"        
"Moisture ratio deficit for fq = 0.5"           
"Power of moisture ratio deficit"        
"Value of 'm' when FR = 0"        
"Value of 'fNutr' when FR = 0"        
"Power of (1-FR) in 'fNutr'"        
"Maximum stand age used in age modifier"        
"Power of relative age in function for fAge"        
"Relative age to give fAge = 0.5"       
"Maximum litterfall rate"        
"Litterfall rate at t = 0"        
"Age at which litterfall rate has median value"        
"Average monthly root turnover rate"       
"Maximum canopy conductance"       
"LAI for maximum canopy conductance"        
"Defines stomatal response to VPD"        
"Canopy boundary layer conductance"        
"Max. stem mass per tree @ 1000 trees/hectare"        
"Power in self-thinning rule"        
"Fraction mean single-tree foliage biomass lost per dead tree"        
"Fraction mean single-tree root biomass lost per dead tree"        
"Fraction mean single-tree stem biomass lost per dead tree"        
"Specific leaf area at age 0"        
"Specific leaf area for mature leaves"        
"Age at which specific leaf area = (SLA0+SLA1)/2"        
"Extinction coefficient for absorption of PAR by canopy"        
"Age at canopy cover"       
"Maximum proportion of rainfall evaporated from canopy"        
"LAI for maximum rainfall interception"        
"Canopy quantum efficiency"        
"Ratio NPP/GPP"       
"Branch and bark fraction at age 0"        
"Branch and bark fraction for mature stands"        
"Age at which fracBB = (fracBB0+fracBB1)/2"        
"Minimum basic density - for young trees"        
"Maximum basic density - for older trees"        
"Age at which rho = (rhoMin+rhoMax)/2"        
"Intercept of net v. solar radiation relationship"        
"Slope of net v. solar radiation relationship"        
"Molecular weight of dry matter"        
"Conversion of solar radiation to PAR" 
```
