---
title: "Additional Resources and Examples"
---

### 📚 Helpful Resources

The 3-PG website hosted by the UBC Faculty of Forestry contains several helpful documents related to model development, descriptions, studies and additional background information: [UBC 3-PG Website](https://3pg.forestry.ubc.ca/).

### 📄 Example Parameter Files

Below is an example of a generic site template. Note how variables can be provided as a constant or a raster (Site.txt):

``` {.custom-block style="background-color: #f0f0f0; color: black;"}
//Temporary Site definition file generated by 3-PG Toolbox
"Model mode"  3PG
"Output directory"  D:\3-PGS_MODEL
//Initial values
"Latitude"      C:\Program Files\3-PG Toolbox V2-5\uslatit.tif
"Fertility rating"  C:\Program Files\3-PG Toolbox V2-5\fert.tif
"Soil class"      3
"Maximum ASW"    C:\Program Files\3-PG Toolbox V2-5\sawater.tif
"Minimum ASW"    0
"Start age"      1
"End Age"      2004
"Start month"    1
"Year planted"    2000
"WFi"        1
"WRi"        0.8
"WSi"        2
"StemNoi"        500
"ASWi"        90

//Satellite only data

//Age Dependant Fertility Modifiers

//Series Data
"Tavg"     D:\3-PGS\CLIMATE\AVTEMP\tavg_01.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_02.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_03.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_04.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_05.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_06.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_07.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_08.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_09.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_10.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_11.tif     D:\3-PGS\CLIMATE\AVTEMP\tavg_12.tif
"Rain"     D:\3-PGS\CLIMATE\RAIN\rain_01.tif     D:\3-PGS\CLIMATE\RAIN\rain_02.tif     D:\3-PGS\CLIMATE\RAIN\rain_03.tif     D:\3-PGS\CLIMATE\RAIN\rain_04.tif     D:\3-PGS\CLIMATE\RAIN\rain_05.tif     D:\3-PGS\CLIMATE\RAIN\rain_06.tif     D:\3-PGS\CLIMATE\RAIN\rain_07.tif     D:\3-PGS\CLIMATE\RAIN\rain_08.tif     D:\3-PGS\CLIMATE\RAIN\rain_09.tif     D:\3-PGS\CLIMATE\RAIN\rain_10.tif     D:\3-PGS\CLIMATE\RAIN\rain_11.tif     D:\3-PGS\CLIMATE\RAIN\rain_12.tif
"Vpd"     D:\3-PGS\CLIMATE\VPD\vpd_01.tif     D:\3-PGS\CLIMATE\VPD\vpd_02.tif     D:\3-PGS\CLIMATE\VPD\vpd_03.tif     D:\3-PGS\CLIMATE\VPD\vpd_04.tif     D:\3-PGS\CLIMATE\VPD\vpd_05.tif     D:\3-PGS\CLIMATE\VPD\vpd_06.tif     D:\3-PGS\CLIMATE\VPD\vpd_07.tif     D:\3-PGS\CLIMATE\VPD\vpd_08.tif     D:\3-PGS\CLIMATE\VPD\vpd_09.tif     D:\3-PGS\CLIMATE\VPD\vpd_10.tif     D:\3-PGS\CLIMATE\VPD\vpd_11.tif     D:\3-PGS\CLIMATE\VPD\vpd_12.tif
"solar radtn"     D:\3-PGS\CLIMATE\SOLAR\swrad_01.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_02.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_03.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_04.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_05.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_06.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_07.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_08.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_09.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_10.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_11.tif     D:\3-PGS\CLIMATE\SOLAR\swrad_12.tif
"Frost Days"     D:\3-PGS\CLIMATE\FROST\frost_01.tif     D:\3-PGS\CLIMATE\FROST\frost_02.tif     D:\3-PGS\CLIMATE\FROST\frost_03.tif     D:\3-PGS\CLIMATE\FROST\frost_04.tif     D:\3-PGS\CLIMATE\FROST\frost_05.tif     D:\3-PGS\CLIMATE\FROST\frost_06.tif     D:\3-PGS\CLIMATE\FROST\frost_07.tif     D:\3-PGS\CLIMATE\FROST\frost_08.tif     D:\3-PGS\CLIMATE\FROST\frost_09.tif     D:\3-PGS\CLIMATE\FROST\frost_10.tif     D:\3-PGS\CLIMATE\FROST\frost_11.tif     D:\3-PGS\CLIMATE\FROST\frost_12.tif

//Management Tables

//Outputs
"fSW"  fSW.tif  2001  1 month 1
"fVPD"  fVPD.tif  2001  1 month 1
"fT"  fT.tif  2001  1 month 1
"fNutr"  fNutr.tif  2001  1 month 1
"fFrost"  fFrost.tif  2001  1 month 1
"FRout"  FR.tif  2001  1 month 1
```

A generic species template for pine is provided below (Species_Generic_Pine.txt):

``` {.custom-block style="background-color: #f0f0f0; color: black;"}
///Temporary Species definition file generated by 3-PG Toolbox
"Foliage:stem partitioning ratio @ D=2 cm"        1.53
"Foliage:stem partitioning ratio @ D=20 cm"        0.55
"Constant in the stem mass v. diam. relationship"        0.0073
"Power in the stem mass v. diam. relationship"        3.282
"Maximum fraction of NPP to roots"        0.8
"Minimum fraction of NPP to roots"        0.25
"Minimum temperature for growth"        -7
"Optimum temperature for growth"       15
"Maximum temperature for growth"       30
"Days production lost per frost day"        1.0
"Moisture ratio deficit for fq = 0.5"        0.7
"Power of moisture ratio deficit"        9
"Value of 'm' when FR = 0"        0
"Value of 'fNutr' when FR = 0"        1
"Power of (1-FR) in 'fNutr'"        1
"Maximum stand age used in age modifier"        200
"Power of relative age in function for fAge"        4
"Relative age to give fAge = 0.5"        0.95
"Maximum litterfall rate"        0.015
"Litterfall rate at t = 0"        0.01
"Age at which litterfall rate has median value"        36
"Average monthly root turnover rate"        0.015
"Maximum canopy conductance"        0.02
"LAI for maximum canopy conductance"        3.33
"Defines stomatal response to VPD"        0.055
"Canopy boundary layer conductance"        0.2
"Max. stem mass per tree @ 1000 trees/hectare"        200
"Power in self-thinning rule"        1.5
"Fraction mean single-tree foliage biomass lost per dead tree"        1
"Fraction mean single-tree root biomass lost per dead tree"        1
"Fraction mean single-tree stem biomass lost per dead tree"        1
"Branch and bark fraction at age 0"        0.75
"Branch and bark fraction for mature stands"        0.15
"Age at which fracBB = (fracBB0+fracBB1)/2"        2
"Minimum basic density - for young trees"        0.45
"Maximum basic density - for older trees"        0.5
"Intercept of net v. solar radiation relationship"        -90
"Slope of net v. solar radiation relationship"        0.8
"Molecular weight of dry matter"        24
"Conversion of solar radiation to PAR"        2.3
"Specific leaf area at age 0"        5.75
"Specific leaf area for mature leaves"        3.1
"Age at which specific leaf area = (SLA0+SLA1)/2"        2
"Extinction coefficient for absorption of PAR by canopy"        0.5
"Age at canopy cover"        20
"Maximum proportion of rainfall evaporated from canopy"        0.15
"LAI for maximum rainfall interception"        3.1
"Canopy quantum efficiency"        0.04
"Ratio NPP/GPP"        0.47
// New parameters
// "Age at which rho = (rhoMin+rhoMax)/2"        4
"Age at which rho = (rho0+rho1)/2"  4.0
"Constant in the stem volume relationship"        0
"Power of DBH in the stem volume relationship"        0
"Power of stocking in the stem volume relationship"        0
"Mortality rate for large t"        0
"Seedling mortality rate (t = 0)"        0
"Age at which mortality rate has median value"        0
"Shape of mortality response"        1.0
"Constant in the stem height relationship"        0
"Power of DBH in the stem height relationship"        0
"Power of stocking in the stem height relationship"        0
//"Species Code"        1
```

An example of the command line prompt necessary to run this example, if the executable and the paths are stored on your D drive in a folder called '3PG_Example':

```         
D:/3PG_Example/3PG.exe -d D:/3PG_Example/Species_Generic_Pine.txt -s D:/3PG_Example/Site.txt
```

### 🗺️ Example Outputs

Add example rasters - potentially link example parameter files to output and add a shapefile or coordinates to area where the study took place to be reproducible?
